### ISSUE TITLE
Fatal error on examples

### ISSUE THREAD

**Issue by asmyers** [haslab/Electrum2#14]
When trying to check the examples with Electrod/nuXmv or Electrod/NuSMV the analyzer emits a fatal error:

<img width="635" alt="Screen Shot 2019-10-09 at 12 33 11" src="https://user-images.githubusercontent.com/122908/66501316-301ee780-ea91-11e9-91c8-fec5d1743737.png">

This is trying to check the example `ring.ele`
Versions:
- Analyzer: Electrum Analyzer 2.0.0.201910072237 (forked from Alloy Analyzer 5.0.0) (build date: 2019-10-07T22:37:05.361Z git 4d7d4a4efc278273e0b5c2ca5b96c06303e1dc17)
 - Electrod: 0.2.3
- NuSMV: *** This is NuSMV 2.6.0 (compiled on Wed Oct 14 15:32:58 2015)
- nuXmv: This is nuXmv 1.1.1 (compiled on Wed Jun  1 10:19:55 2016)
- OS: Darwin 18.7.0 Darwin Kernel Version 18.7.0

```
java -jar electrum2.0.jar -d                                                                                       
Mac classes not there
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by edu.mit.csail.sdg.alloy4whole.SimpleGUI (file:/Users/amyers/Downloads/electrum2.0.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of edu.mit.csail.sdg.alloy4whole.SimpleGUI
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Loaded: libminisat.dylib
Loaded: libminisatprover.dylib
Loaded: liblingeling.dylib
Loaded: libglucose.dylib
Failed to load: libcryptominisat.dylib
Loaded: electrod at /private/var/folders/50/sjyqy83j25n1y2ydjzl5n294000350/T/alloy4tmp40-amyers/binary/electrod
Loaded: NuSMV at /Users/amyers/bin/NuSMV-2.6.0-Darwin/bin
Loaded: nuXmv at /Users/amyers/bin/nuXmv-1.1.1-Darwin/bin
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by grayswandyr** [comment]
Confirmed, thanks. We're looking into this problem.

**Comment by nmacedo** [comment]
Fixed in current versions of Pardinus/Electrod.
