### ISSUE TITLE
Error in next after exhausting forks

### ISSUE THREAD

**Issue by alcinocunha** [haslab/Electrum2#2]
In this model
```
var sig A {}
var sig B extends A {}
run {} for 1
```
if you fork the initial state until no more initial states are possible, and then press next you get this exception:
```
Enumerating...
java.util.NoSuchElementException

An error has occurred!
```

**Comment by nmacedo** [comment]
This raises another question: when we formalised the "fork" operators, we did not consider the "next" random solution. So, the question is, when iterating using "next", do we clear the solutions previously excluded by "fork" or do we start from that history? (I think it should reset.) And vice-versa, can "fork" produce instances previously excluded by "next" iteration? (Here I also think it should reset, but not so sure.)

**Comment by alcinocunha** [comment]
I think no reset is the only coherent behaviour. Next means "return me another instance, excluding the present one plus all the previously excluded". Fork means "return me another instance, excluding all that have the same prefix as the present one plus all the previously excluded".
