### ISSUE TITLE
Are seq supported?

### ISSUE THREAD

**Issue by pkriens** [haslab/Electrum2#21]
I was trying to use 'seq' and ran into the following syntax error on sequniv.als:

![image](https://user-images.githubusercontent.com/200494/84371925-ac4a6b80-abda-11ea-94fe-c9db71d4900a.png)

	class edu.mit.csail.sdg.alloy4.ErrorSyntax: There are 38 possible tokens that can appear here:
	! # ( * @ Int NAME NUMBER STRING String Time ^ after all always before disj eventually fun historically iden int let lone no none once one pred seq set some sum this univ { } ~ 
	edu.mit.csail.sdg.parser.CompParser.syntax_error(CompParser.java:2823)
	edu.mit.csail.sdg.parser.CompParser.parse(CompParser.java:2670)
	edu.mit.csail.sdg.parser.CompParser.alloy_parseStream(CompParser.java:2865)
	edu.mit.csail.sdg.parser.CompUtil.parse(CompUtil.java:497)
	edu.mit.csail.sdg.parser.CompUtil.parseRecursively(CompUtil.java:255)
	edu.mit.csail.sdg.parser.CompUtil.parseRecursively(CompUtil.java:299)
	edu.mit.csail.sdg.parser.CompUtil.parseEverything_fromFile(CompUtil.java:444)
	edu.mit.csail.sdg.alloy4whole.SimpleReporter$SimpleTask1.run(SimpleReporter.java:672)
	edu.mit.csail.sdg.alloy4.WorkerEngine$5.run(WorkerEngine.java:462)
	java.base/java.lang.Thread.run(Unknown Source)

**Comment by grayswandyr** [comment]
The issue here is that we must substitute all `'` characters in legacy models (including those from `util/`, and `seq` relies on `util/sequniv`). Once this is done, we think `seq` should work but we still have to check more thoroughly.

**Comment by nmacedo** [comment]
932943f994eb2544e179ec966c68e9745e4c6e4d fixed the legacy util models.

**Comment by pkriens** [comment]
It is a bit late but I also got some more experience now ...

I am starting to wonder if we should actually use the ' in the first place. I know people are familiar with it but I am becoming afraid that this is going to kill a lot of models out there since this is a pretty big part of Daniel's conventions in his book.

Couldn't we use a backtick (`) for the use in Electrum?

**Comment by grayswandyr** [comment]
As this will be a major version, I think it's acceptable to make a breaking change. But we will discuss the situation internally and see what we can do, please just be patient.

**Comment by pkriens** [comment]
I am very patient :-) However, this change is larger than I thought and by using another character we bypass these issues for, imho, a very small cost.

**Comment by grayswandyr** [comment]
I wouldn't base my choice on this, but backticks wouldn't play nice with Markdown :smile:

**Comment by pkriens** [comment]
Only in the non-alloy parts. But that is an issue :-)

Although, you double the backticks in the text section:
 
                   ``Use `code` in your Markdown file.``

``Use `code` in your Markdown file.``
