### ISSUE TITLE
module imports from .md files search for mangled filenames

### ISSUE THREAD

**Issue by keithb-b** [haslab/Electrum2#40]
When I import a module into a module defined in a .md file the search seems to look for a file with the last character of the importing module appended. 

For example, if I have `open ExampleImport ` in a file `example.md`, then a run fails with message

```
File cannot be found.
/Users/keithb/Documents/Alloy/Vehicles/ExampleImporte.md (No
such file or directory)

```
whereas if I have `open ExampleImport ` in a file `exampleq.md` then a run fails with error

```
File cannot be found.
/Users/keithb/Documents/Alloy/Vehicles/ExampleImportq.md (No
such file or directory)
```

This occurs with Electrum Analyzer 2.0.0.201910111016 running from the .jar on java 14.0.2 on OSX 10.13.6

**Comment by nmacedo** [comment]
Thanks for reporting, fixed once 2.1 goes live.
