### ISSUE TITLE
Warn or reject predicate name plus block in command

### ISSUE THREAD

**Issue by zsfre** [haslab/Electrum2#50]
```
pred thing {...

run thing {
  doSomethingElse
}
```
is confusing because it looks like `run` will run the predicate `thing` plus `doSomethingElse`. The language spec says that `run` can be followed by a predicate name *or* a block, so both is unspecified.

Suggest either adding a warning where the name matches a predicate name, or disallowing as per the documentation.

**Comment by nmacedo** [comment]
This is an issue on the Alloy5 side (https://github.com/AlloyTools/org.alloytools.alloy) rather than of Electrum, which mainly extends it with the temporal functionalities.

**Comment by zsfre** [comment]
Understood. I wasn't sure where to put it.
