### ISSUE TITLE
Not possible to generate next example

### ISSUE THREAD

**Issue by sz332** [haslab/Electrum2#59]
In alloytools when I run my model and open the browser there is a button Next which generates a new example. It seems that during the interface redesign this functionality is somehow lost. Is it really removed or I just missed something?

**Comment by nmacedo** [comment]
With traditional Alloy models (i.e., without temporal constructs) the "Next" button, and the visualizer in general, should remain unchanged. There was however a bug that was preventing showing the trace visualizer even for static models, this has been fixed.

**Comment by sz332** [comment]
Is the change applied in the original AlloyTools as well, or only in Electrum2?

**Comment by nmacedo** [comment]
It's live on Electrum2, waiting to be accepted at AlloyTools.
