### ISSUE TITLE
Syntax checker doesn't find all erroneous semicolons and it can cause strange behavior silently

### ISSUE THREAD

**Issue by ssiemonsma** [haslab/Electrum2#64]
Since many programmers have a strong habit of ending lines with semicolons, it seems extra dangerous for the syntax checker to not catch these.  In my experience, if you end a line with a semicolon inside of a braced code block, the syntax checker does not find it.  As long the semicolon isn't in the last line of the braced code block, the syntax checker won't complain at all, and the semicolon seems to cause strange behavior within the traces (completely silently).

I double checked with vanilla Alloy Analyzer 5.1, and its syntax checker is able to find erroneous semicolons just fine.

I am running Electrum 2.1.5 with Java 1.8.0.

**Comment by grayswandyr** [comment]
Hi, `;` is in fact an Electrum operator. `p;q` means `p and after q`. The operator is right associative, meaning `p;q;r` is `p;(q;r)`. This is useful when you want to specify scenarios.

**Comment by ssiemonsma** [comment]
But is there any reason the syntax checker shouldn't complain about a semicolon floating at the end of a line?  Again, this causes internally inconsistent traces.

**Comment by grayswandyr** [comment]
I'm not sure to understand:
```
p;
q
```
means `p;q`, which means `p and after q`. So this is perfectly correct Electrum.

OTOH, that is incorrect:
```
p;
}
```
as `;` should be followed by a constraint before closing braces. 

In programming languages, `;` does not have to appear at the end of a line, this is just a (sane) convention.

**Comment by ssiemonsma** [comment]
Ok, nevermind, I think I understand the behavior of the trace now.  Thanks!

**Comment by ssiemonsma** [comment]
Can I ask where the semicolon is mentioned as an operator in the documentation?  When I was trying to understand this behavior previously, I could not find it mentioned.

**Comment by grayswandyr** [comment]
Yeah, for the moment, the only full documentation is the [language specification](https://github.com/haslab/Electrum2/wiki/Language) (the part about `;` is at the bottom of the page), sorry about that. We are in the process of writing user-oriented documentation, however.
